module.exports = {
  loggedIn:false,
  appInstalled: false,
  lat:30.76,
  long:76.56,
  authKey: '',
  refreshKey: '',
  termCondition: '',
  privacyURL: '',
  bToken: '',
  userId: '',
  userName: '',
  appHomeTitle: '',
  appVersion: '',
  profilePic: '',
  primaryColor: '#13B58C',
  secondaryColor: '#13B58C',
  firebaseToken: '',
  defaultCurrency: '',
  intoScreen: [],
  accountID: '',
  hideTabbar: true,
  appSharePath: 'classbubs://',
  apiVersion: '2020-08-27',
  stripePublishKey: 'pk_test_51HPL2tIRWtZLg0gEHG08IMqnNrLeZDRd8M9fSnqQ5Sqj3NIfghpC6pMthvLb6ccwg7h8SECQUDqxlCYU35lxHexJ00qhCHpODu',
  dsnSentry: 'https://a36e7a2a75764b44aacc1400414d0fca@o396771.ingest.sentry.io/5896058',
  firebaseChatPath: '/tradly_dev/',
  tenantID:'tradlysocial',
}