
module.exports = {
  login: 'login',
  signup: 'signup',
  forgotpassword: 'forgotpassword',
  passwordreset: 'passwordreset',
  otp:'otp',
  intro:'intro',
  addstore: 'addstore',
  home: 'home',
  search: 'search',
  addproduct: 'addproduct',
  more:'more',
  product:'product',
  cart:'cart',
  shipping:'shipping',
  address: 'address',
  storedetail:'storedetail',
  myorders:'myorders',
  orderdetail:'orderdetail',
  addvariant:'addvariant',
  producttime: 'producttime',
  variant: 'variant',
  editprofile: 'editprofile',
  sales: 'sales',
  payments:'payments',
  invite:'invite',
  category:'category',
  filter: 'filter',
  productlist:'productlist',
  general: 'general',
  bookingconformation: 'bookingconformation',
  notification: 'notification',
  mapview:'mapview',
  map:'map',

}