module.exports  = {
  OnBoardings: 'OnBoardings',
  SignIn: 'SignIn',
  SignUp: 'SignUp',
  Verification: 'Verification',
  ForgotPassword: 'ForgotPassword',
  BottomTabbar: 'BottomTabbar',
  Home:'Home',
  Category: 'Category',
  AttributeList: 'AttributeList',
  AddressList: 'AddressList',
  More:'More',
  CreateStore: 'CreateStore',
  MyStore: 'MyStore',
  Profile: 'Profile',
  AddEvent: 'AddEvent',
  Currency: 'Currency',
  EventTiming: 'EventTiming',
  AddVariant: 'AddVariant',
  VariantList: 'VariantList',
  AddVariantValue: 'AddVariantValue',
  Filter: 'Filter',
  Sort: 'Sort',
  EventDetail: 'EventDetail',
  ChatScreen: 'ChatScreen',
}