module.exports  = {
  OnBoardings: 'OnBoardings',
  SignIn: 'SignIn',
  SignUp: 'SignUp',
  Verification: 'Verification',
  ForgotPassword: 'ForgotPassword',
  BottomTabbar: 'BottomTabbar',
  Home:'Home',
  CategoryList: 'CategoryList',
  AttributeList: 'AttributeList',
  AddressList: 'AddressList',
  More:'More',
  CreateStore: 'CreateStore',
  MyStore: 'MyStore',
  Profile: 'Profile',
  AddEvent: 'AddEvent',
  Currency: 'Currency',
  EventTiming: 'EventTiming',
  AddVariant: 'AddVariant',
  VariantList: 'VariantList',
  AddVariantValue: 'AddVariantValue',
  Filter: 'Filter',
  Category: 'Category',
  EventDetail: 'EventDetail',
  ChatScreen: 'ChatScreen',
  Explore: 'Explore',
  EventList: 'EventList',
  ConfirmBooking: 'ConfirmBooking',
  MyOrders: 'MyOrders',
  OrderDetail:'OrderDetail',
  PaymentScreen:'PaymentScreen',
  MySale: 'MySale',
  PayoutsScreen: 'PayoutsScreen',
  InviteFriend: 'InviteFriend',
  Notifications:'Notifications' ,
  Schedule:'Schedule',
  MyCart: 'MyCart',
  Shipment: 'Shipment',
  AddAddress: 'AddAddress',
  Language:'Language',
  ResetPassword:'ResetPassword',
  StoreList:'StoreList',
  MangoPaySetup:'MangoPaySetup',
}