require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.1'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'tradlyEvent' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'tradlyEventTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    installer.pods_project.targets.each do |target|
      if target.name == 'RCT-Folly'
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FOLLY_CFG_NO_COROUTINES=1'
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
        end
      end
    end
    # Patch RCT-Folly New.h for Xcode 26 / iOS 26 SDK aligned new issue
    folly_new = File.join(installer.sandbox.root, 'RCT-Folly/folly/lang/New.h')
    if File.exist?(folly_new)
      FileUtils.chmod(0644, folly_new) rescue nil
      text = File.read(folly_new)
      patched = text
        .gsub('constexpr auto op_new_builtin_ =', 'constexpr auto op_new_builtin_ = false &&')
        .gsub('constexpr auto op_del_builtin_ =', 'constexpr auto op_del_builtin_ = false &&')
        .gsub('constexpr auto cpp_aligned_new_ = __cpp_aligned_new >= 201606;', 'constexpr auto cpp_aligned_new_ = false;')
        .gsub(
          "  FOLLY_NODISCARD FOLLY_ERASE void* operator()( //\n      std::size_t const s,\n      std::align_val_t const a) const //\n      noexcept(noexcept(::operator new(0))) {\n    return detail::op_new_<detail::cpp_aligned_new_>(s, a);\n  }\n  FOLLY_NODISCARD FOLLY_ERASE void* operator()( //\n      std::size_t const s,\n      std::align_val_t const a,\n      std::nothrow_t const& nt) const noexcept {\n    return detail::op_new_<detail::cpp_aligned_new_>(s, a, nt);\n  }",
          "  FOLLY_NODISCARD FOLLY_ERASE void* operator()( //\n      std::size_t const s,\n      std::align_val_t const a) const //\n      noexcept(noexcept(::operator new(0))) {\n    return detail::op_new_<true>(s);\n  }\n  FOLLY_NODISCARD FOLLY_ERASE void* operator()( //\n      std::size_t const s,\n      std::align_val_t const a,\n      std::nothrow_t const& nt) const noexcept {\n    return detail::op_new_<true>(s, nt);\n  }"
        )
        .gsub(
          "  FOLLY_ERASE void operator()( //\n      void* const p,\n      std::align_val_t const a) const noexcept {\n    return detail::op_del_<detail::cpp_aligned_new_>(p, a);\n  }\n  FOLLY_ERASE void operator()( //\n      void* const p,\n      std::size_t const s,\n      std::align_val_t const a) const noexcept {\n    return detail::do_op_del_sized_<detail::cpp_aligned_new_>(p, s, a);\n  }",
          "  FOLLY_ERASE void operator()( //\n      void* const p,\n      std::align_val_t const a) const noexcept {\n    return detail::op_del_<true>(p);\n  }\n  FOLLY_ERASE void operator()( //\n      void* const p,\n      std::size_t const s,\n      std::align_val_t const a) const noexcept {\n    return detail::do_op_del_sized_<true>(p, s);\n  }"
        )
      File.write(folly_new, patched) if patched != text
    end
  end
end
